services:
  nginx:
    build:
      context: ./services/nginx
      dockerfile: Dockerfile
    container_name: transcendence_nginx
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./services/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./services/nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - frontend
      - backend
    networks:
      - transcendence-net

  frontend:
    build:
      context: ./services/frontend
      dockerfile: Dockerfile
      target: dev
    container_name: transcendence_frontend
    volumes:
      - ./services/frontend:/app
      - frontend_node_modules:/app/node_modules
    ports:
      - "5173:5173"
    networks:
      - transcendence-net

  backend:
    build:
      context: ./services/backend
      dockerfile: Dockerfile
    container_name: transcendence_backend
    networks:
      - transcendence-net
    ports:
      - "3000:3000"
    volumes:
      - ./services/backend/data:/app/data
      # - backend_data:/app

volumes:
  frontend_node_modules:
  backend_data:

networks:
  transcendence-net:
    driver: bridge