services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro # Read-only mount
      - prometheus_data:/prometheus
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "9090:9090"
    networks:
      - transcendence-net
    restart: unless-stopped
    command:
      - '--storage.tsdb.retention.time=15d' # Retain data for 15 days

  grafana:  # Grafana for visualizing Prometheus data
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3001:3000"
    networks:
      - transcendence-net
    depends_on:
      - prometheus
    volumes:
      - grafana_data:/var/lib/grafana
  
  nginx:
    build:
      context: ./services/nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./services/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./services/nginx/ssl:/etc/nginx/ssl:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - frontend
      - backend
    networks:
      - transcendence-net

  nginx-exporter:  # Prometheus exporter for Nginx
    image: nginx/nginx-prometheus-exporter:latest
    container_name: nginx-exporter
    command:
      - -nginx.scrape-uri=http://nginx:80/stub_status
    ports:
      - "9113:9113"
    networks:
      - transcendence-net
    depends_on:
      - nginx

  frontend:
    build:
      context: .
      dockerfile: ./services/frontend/Dockerfile
      target: dev
    container_name: frontend
    volumes:
      - ./services/frontend:/app/services/frontend
      - ./packages/shared:/app/packages/shared
    ports:
      - "5173:5173"
    networks:
      - transcendence-net

  backend:
    build:
      context: .
      dockerfile: ./services/backend/Dockerfile
    container_name: backend
    networks:
      - transcendence-net
    ports:
      - "3000:3000"
    volumes:
      - ./services/backend/data:/app/services/backend/data
      # - backend_data:/app
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  prometheus_data:
  frontend_node_modules:
  backend_data:
  grafana_data:

networks:
  transcendence-net:
    driver: bridge