global:
  resolve_timeout: 5m

route:
  receiver: "slack-receiver"
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 5m
  group_by: ['alertname', 'severity']

receivers:
  - name: "slack-receiver"
    slack_configs:
      - api_url: ${SLACK_WEBHOOK_URL}
        username: "alertmanager"
        title: '{{ .CommonLabels.alertname }} - {{ .Status | toUpper }}'
        text: |-
          {{ range .Alerts }}
          *{{ if .Annotations.summary }}{{ .Annotations.summary }}{{ else }}{{ .Labels.alertname }}{{ end }}*
          {{- if .Annotations.description }}
          {{ .Annotations.description }}
          {{- end }}
          {{ end }}
        send_resolved: true
