groups:
  - name: basic.alerts
    rules:
      - alert: BackendDown
        expr: up{job="backend"} == 0
        for: 20s
        labels:
          severity: critical
          team: backend
        annotations:
          summary: "Backend service down"
          description: "The backend service (instance {{ $labels.instance }}) is not responding."