global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']
  - job_name: 'backend'
    static_configs:
      - targets: ['backend:3000']
  # - job_name: 'frontend'
  #   static_configs:
  #     - targets: ['frontend:5173']


# remote_write:               # Remote write configuration for Grafana Cloud
#   - url: <https://your-remote-write-endpoint>
#     basic_auth:
#       username: <your user name>
#       password: <Your Grafana.com API Key>