groups:
  - name: Transcendence
    rules:
      - alert: Program is running
        expr: vector(1)
        for: 0s
        labels:
          severity: info
        annotations:
          summary: "The Game is up"
          description: "Fires when the game is starting."